# Generated by Django 3.1.7 on 2021-03-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('open_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.BooleanField(null=True)),
                ('head', models.CharField(max_length=500, null=True)),
                ('bigHead', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('fan', models.IntegerField(default=0)),
                ('follow', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('public_count', models.IntegerField(default=0)),
                ('friend_count', models.IntegerField(default=0)),
                ('private_count', models.IntegerField(default=0)),
                ('total_like_count', models.IntegerField(default=0)),
                ('total_comment_count', models.IntegerField(default=0)),
                ('total_view_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('photo_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('caption', models.CharField(default='Default Caption', max_length=500)),
                ('cover', models.CharField(default='Default Cover', max_length=500)),
                ('play_url', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('pending', models.BooleanField()),
                ('labels', models.ManyToManyField(to='app.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
